#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
Reproducible WGCNA pipeline for Alzheimer's Disease co-expression analysis
================================================================================

This script is a clean, honest, end-to-end re-implementation of the analysis
reported in "Weighted Gene Co-expression Network Analysis Reveals Functionally
Coherent Gene Networks Associated with Alzheimer's Disease Pathology".

It is written specifically to FIX the problems raised in peer review. Each fix
is annotated inline with the tag  [REV-n]  referring to the reviewer's numbered
comment, so you can trace every methodological decision back to a requirement.

    [REV-1] One single, clearly named primary dataset, used consistently.
    [REV-2] Every downstream analysis derives from THAT dataset (or, if external,
            is loaded as an explicitly declared secondary dataset).
    [REV-3] Soft-threshold power chosen by the scale-free-topology criterion,
            with the diagnostic plots saved. NOT hard-coded to beta = 1.
    [REV-4] Module sizes are computed from the partition and ALWAYS sum to the
            number of retained genes (a sanity assert enforces this).
    [REV-5] No placeholder text / duplicated blocks -- this is code, not prose,
            but the OUTPUT tables it produces are what the manuscript should cite.
    [REV-6] Only analysis-derived figures are produced here. Background
            schematics (tau/amyloid cartoons, KEGG textbook maps) are NOT
            generated by an analysis and must be handled separately in the paper.
    [REV-7] Module preservation is actually COMPUTED and a Z-summary table saved.
    [REV-8] Module biology is labelled from enrichment OUTPUT, not asserted, so
            the turquoise/blue interpretation cannot contradict itself.
    [REV-9] Covariates (sex, age, region, batch) are modelled and removed before
            network construction; module-trait tests use both binary AD status
            and continuous pathology traits; exact adjusted p-values, odds
            ratios and the enrichment background are all reported.

PRIMARY DATASET (anchor of the whole study):
    GSE29378  -- Miller, Woltjer, Goodenbour, Horvath, Geschwind (2013),
                 human post-mortem hippocampus (CA1 + CA3 subfields),
                 AD vs cognitively-normal controls, Illumina microarray,
                 ~63 samples. Openly downloadable from NCBI GEO.

VALIDATION / PRESERVATION DATASET (declared secondary):
    GSE48350  -- independent hippocampus cohort, Affymetrix U133 Plus 2.0.
                 Used ONLY for module-preservation statistics.

--------------------------------------------------------------------------------
Requirements (install once):
    pip install GEOparse dynamicTreeCut gseapy statsmodels scikit-learn \
                scipy numpy pandas matplotlib seaborn

Run:
    python ad_wgcna_pipeline.py                 # full pipeline on GSE29378
    python ad_wgcna_pipeline.py --skip-download  # reuse cached GEO files
    python ad_wgcna_pipeline.py --network-type signed   # signed network (default)

All outputs (tables + figures + a run log) land in ./results/ .
--------------------------------------------------------------------------------
NOTE ON NETWORK TYPE:
    The original manuscript used an UNSIGNED network with beta = 1. beta = 1 is
    almost never appropriate -- it leaves the adjacency equal to |correlation|,
    so no soft-thresholding actually happens and the scale-free assumption is
    not enforced. This pipeline DEFAULTS TO A SIGNED network and PICKS beta from
    the data. Expect beta ~ 12-18 (signed) or ~ 6 (unsigned) on real brain data.
================================================================================
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import warnings
from dataclasses import dataclass, field
from datetime import datetime

import numpy as np
import pandas as pd
from scipy.cluster.hierarchy import linkage, fcluster
from scipy.spatial.distance import squareform
from scipy.stats import fisher_exact, t as t_dist
from statsmodels.stats.multitest import multipletests

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

# ------------------------------------------------------------------------------
# 0. CONFIGURATION
# ------------------------------------------------------------------------------

@dataclass
class Config:
    # --- datasets [REV-1, REV-2] ----------------------------------------------
    primary_gse: str = "GSE29378"          # the ONE dataset the paper is about
    validation_gse: str = "GSE48350"       # secondary, preservation only
    geo_dir: str = "geo_cache"

    # --- preprocessing [REV-9] ------------------------------------------------
    # Phenotype / covariate fields are parsed from GEO 'characteristics' lines.
    # Edit the regexes in parse_metadata() if GEO field names differ.
    min_mean_expr: float = 0.0             # drop genes below this mean (log scale)
    var_quantile_keep: float = 0.50        # keep top X% most-variable genes
    n_top_genes_network: int = 5000        # WGCNA on the most variable N genes
    outlier_z_thresh: float = 2.5          # sample outlier cut on connectivity Z
    covariates: tuple = ("sex", "age", "region")  # regressed out before network

    # --- network construction [REV-3] -----------------------------------------
    network_type: str = "signed"           # "signed" | "unsigned" | "signed hybrid"
    powers: tuple = tuple(list(range(1, 11)) + list(range(12, 31, 2)))
    sft_r2_cut: float = 0.85               # scale-free topology target R^2
    manual_power: int = 0                  # >0 overrides data-driven beta (--power)

    # --- module detection [REV-4] ---------------------------------------------
    deep_split: int = 2
    min_module_size: int = 30
    merge_cut_height: float = 0.25         # merge modules with ME-dissimilarity < this

    # --- module-trait & hub genes [REV-8, REV-9] ------------------------------
    mt_abs_r_cut: float = 0.40
    mt_padj_cut: float = 0.01
    hub_mm_cut: float = 0.80
    hub_gs_cut: float = 0.40

    # --- enrichment [REV-9] ----------------------------------------------------
    enrichr_gene_sets: tuple = ("GO_Biological_Process_2021", "KEGG_2021_Human")
    enrichment_fdr_cut: float = 0.05
    run_enrichr: bool = True               # set False for offline runs

    # --- preservation [REV-7] -------------------------------------------------
    preservation_perms: int = 200
    preservation_max_genes: int = 4000     # subsample for tractable permutations

    # --- reproducibility -------------------------------------------------------
    seed: int = 42
    out_dir: str = "results"


CFG = Config()

# ------------------------------------------------------------------------------
# Curated AD risk-gene panel  [REV-9: this IS the test set; background declared below]
# Compiled from Bellenguez et al. 2022 GWAS + Jansen 2019 + classic loci.
# Replace/extend with your own curated list; keep it version-controlled.
# ------------------------------------------------------------------------------
AD_RISK_GENES = sorted(set("""
APOE APP PSEN1 PSEN2 TREM2 BIN1 CLU PICALM CR1 ABCA7 MS4A6A MS4A4E CD33 CD2AP
EPHA1 SORL1 INPP5D MEF2C HLA-DRB5 PTK2B SLC24A4 ZCWPW1 CELF1 FERMT2 CASS4
NME8 DSG2 ABCA1 ADAM10 ADAMTS1 ALPK2 AP4E1 AP4M1 APH1B BCKDK BLNK BZRAP1 CCDC6
CD55 CLNK CNTNAP2 ECHDC3 GRN HAVCR2 HESX1 HS3ST1 IGH IKZF1 IL34 IQCK KAT8 KLF16
LILRB2 MAF MAPT MME NCK2 PLCG2 PRKD3 RHOH SCIMP SHARPIN SIGLEC11 SPI1 SPPL2A SYK
TNIP1 TPCN1 TSPOAP1 USP6NL WWOX ABI3 ACE ADAMTS4 ANKH APOC1 CTSH DOC2A EED FOXF1
GRIN2B JAZF1 NDUFAF6 RBCK1 SEC61G SLC2A4RG SORT1 TMEM106B UMAD1 WDR12 WNT3
""".split()))


# ------------------------------------------------------------------------------
# Logging
# ------------------------------------------------------------------------------
def setup_logging(out_dir: str) -> logging.Logger:
    os.makedirs(out_dir, exist_ok=True)
    log = logging.getLogger("ad_wgcna")
    log.setLevel(logging.INFO)
    log.handlers.clear()
    fmt = logging.Formatter("%(asctime)s | %(levelname)-7s | %(message)s",
                            "%H:%M:%S")
    sh = logging.StreamHandler(sys.stdout); sh.setFormatter(fmt); log.addHandler(sh)
    fh = logging.FileHandler(os.path.join(out_dir, "run.log"), mode="w")
    fh.setFormatter(fmt); log.addHandler(fh)
    return log


# ==============================================================================
# 1. DATA ACQUISITION & METADATA PARSING                                [REV-1,2,9]
# ==============================================================================
def download_geo(gse_id: str, cfg: Config, log):
    """Download a GEO series with GEOparse and return the GSE object."""
    import GEOparse
    os.makedirs(cfg.geo_dir, exist_ok=True)
    log.info(f"Loading {gse_id} from GEO (cache: {cfg.geo_dir}) ...")
    gse = GEOparse.get_GEO(geo=gse_id, destdir=cfg.geo_dir, silent=True,
                           annotate_gpl=True)
    return gse


def build_expression_matrix(gse, log) -> pd.DataFrame:
    """
    Return a probe x sample expression DataFrame.
    Works for typical single-platform microarray series.
    """
    expr = gse.pivot_samples("VALUE")          # rows = probes, cols = GSM ids
    expr = expr.apply(pd.to_numeric, errors="coerce")
    expr = expr.dropna(how="all")
    log.info(f"Raw expression matrix: {expr.shape[0]} probes x {expr.shape[1]} samples")
    return expr


def map_probes_to_genes(gse, expr: pd.DataFrame, log) -> pd.DataFrame:
    """
    Collapse probes to gene symbols using the platform annotation.
    Strategy = MaxMean: for each gene keep the probe with the highest mean signal
    (mirrors WGCNA::collapseRows 'MaxMean'). [REV-9 reproducibility]
    """
    gpl = list(gse.gpls.values())[0]
    ann = gpl.table.copy()
    # find a gene-symbol column heuristically
    candidates = ["Gene Symbol", "Gene symbol", "GENE_SYMBOL", "Symbol",
                  "gene_symbol", "ILMN_Gene", "GeneSymbol", "Gene_Symbol"]
    sym_col = next((c for c in candidates if c in ann.columns), None)
    id_col = "ID" if "ID" in ann.columns else ann.columns[0]
    if sym_col is None:
        log.warning("No gene-symbol column found in platform annotation; "
                    "keeping probe IDs. Inspect gpl.table.columns and set sym_col.")
        return expr
    ann = ann[[id_col, sym_col]].dropna()
    ann[sym_col] = (ann[sym_col].astype(str)
                    .str.split("///").str[0].str.strip())     # first symbol
    ann = ann[ann[sym_col].str.len() > 0]
    probe2gene = dict(zip(ann[id_col].astype(str), ann[sym_col]))

    expr = expr.copy()
    expr.index = expr.index.astype(str)
    expr["__gene__"] = expr.index.map(probe2gene)
    expr = expr.dropna(subset=["__gene__"])
    expr["__mean__"] = expr.drop(columns="__gene__").mean(axis=1)
    # MaxMean collapse
    expr = (expr.sort_values("__mean__", ascending=False)
                .drop_duplicates("__gene__", keep="first"))
    expr = expr.set_index("__gene__").drop(columns="__mean__")
    expr.index.name = "gene"
    log.info(f"After probe->gene MaxMean collapse: {expr.shape[0]} genes")
    return expr


def parse_metadata(gse, log) -> pd.DataFrame:
    """
    Parse per-sample phenotype from GEO 'characteristics_ch1'.
    Produces columns: AD (0/1), sex, age, region, batch (best effort).
    EDIT the keyword lists below to match the exact wording in your series.
    [REV-1 single dataset, REV-9 covariates declared]
    """
    rows = {}
    for gsm_id, gsm in gse.gsms.items():
        meta = " ; ".join(gsm.metadata.get("characteristics_ch1", [])).lower()
        title = " ".join(gsm.metadata.get("title", [])).lower()
        blob = meta + " ; " + title

        # diagnosis
        ad = np.nan
        if any(k in blob for k in ["alzheimer", "ad ", ": ad", "case", "disease: ad"]):
            ad = 1
        if any(k in blob for k in ["control", "normal", "non-demented", "nd ",
                                   "cognitively normal", "ctrl"]):
            ad = 0 if np.isnan(ad) else ad
        # sex
        sex = np.nan
        if any(k in blob for k in [" female", "sex: f", "gender: f", "f-ad", "f-control"]):
            sex = 0
        if any(k in blob for k in [" male", "sex: m", "gender: m", "m-ad", "m-control"]):
            sex = 1
        # age
        age = np.nan
        import re
        m = re.search(r"age[^0-9]{0,8}(\d{2,3})", blob)
        if m:
            age = float(m.group(1))
        # region (GSE29378 = CA1 / CA3)
        region = np.nan
        if "ca1" in blob: region = "CA1"
        elif "ca3" in blob: region = "CA3"
        # braak / cerad if present (continuous traits) [REV-9]
        braak = np.nan
        mb = re.search(r"braak[^0-9]{0,8}(\d)", blob)
        if mb: braak = float(mb.group(1))

        rows[gsm_id] = dict(AD=ad, sex=sex, age=age, region=region, braak=braak)

    meta = pd.DataFrame(rows).T
    log.info("Parsed metadata (head):\n" + meta.head().to_string())
    n_ad = int((meta["AD"] == 1).sum()); n_ct = int((meta["AD"] == 0).sum())
    log.info(f"Diagnosis counts -> AD: {n_ad}, Control: {n_ct}, "
             f"Unknown: {int(meta['AD'].isna().sum())}")
    if n_ad == 0 or n_ct == 0:
        log.warning("Could not resolve AD/control from metadata automatically. "
                    "Inspect gse.gsms[...].metadata['characteristics_ch1'] and "
                    "edit parse_metadata().")
    return meta


# ==============================================================================
# 2. QC, NORMALISATION & COVARIATE ADJUSTMENT                            [REV-9]
# ==============================================================================
def maybe_log2(expr: pd.DataFrame, log) -> pd.DataFrame:
    if np.nanmax(expr.values) > 50:           # looks like linear-scale intensities
        log.info("Applying log2(x+1) (data appeared to be on a linear scale).")
        expr = np.log2(expr.clip(lower=0) + 1)
    return expr


def filter_genes(expr: pd.DataFrame, cfg: Config, log) -> pd.DataFrame:
    expr = expr.loc[expr.mean(axis=1) >= cfg.min_mean_expr]
    cv = expr.std(axis=1)
    keep = cv >= cv.quantile(1 - cfg.var_quantile_keep)
    expr = expr.loc[keep]
    log.info(f"After expression+variance filtering: {expr.shape[0]} genes")
    # cap at most-variable N for network construction (standard WGCNA practice)
    if expr.shape[0] > cfg.n_top_genes_network:
        top = expr.var(axis=1).sort_values(ascending=False).index[:cfg.n_top_genes_network]
        expr = expr.loc[top]
        log.info(f"Restricted to top {cfg.n_top_genes_network} most-variable genes.")
    return expr


def detect_sample_outliers(datExpr: pd.DataFrame, cfg: Config, log) -> pd.DataFrame:
    """
    datExpr = samples x genes. Flag outliers by standardised total connectivity
    (mirrors WGCNA recommended sample network Z.k approach).
    """
    A = np.corrcoef(datExpr.values)
    np.fill_diagonal(A, 0)
    k = A.sum(axis=1)
    Z = (k - k.mean()) / k.std()
    outliers = datExpr.index[Z < -cfg.outlier_z_thresh]
    if len(outliers):
        log.info(f"Removing {len(outliers)} outlier sample(s): {list(outliers)}")
        datExpr = datExpr.drop(index=outliers)
    else:
        log.info("No sample outliers detected.")
    return datExpr


def adjust_covariates(datExpr: pd.DataFrame, meta: pd.DataFrame,
                      cfg: Config, log) -> pd.DataFrame:
    """
    Regress technical/biological covariates out of each gene (limma
    removeBatchEffect style) while PROTECTING the AD signal of interest.
    [REV-9: sex/age/region/batch modelled and removed; AD kept]
    """
    import statsmodels.api as sm
    covs = [c for c in cfg.covariates if c in meta.columns]
    md = meta.loc[datExpr.index]
    # build design: covariates to remove + AD to retain
    X_parts = []
    for c in covs:
        col = md[c]
        if col.dtype == object:                      # categorical e.g. region
            d = pd.get_dummies(col, prefix=c, drop_first=True).astype(float)
            X_parts.append(d)
        else:
            X_parts.append(col.astype(float).to_frame(c))
    if not X_parts:
        log.info("No covariates available to adjust; skipping covariate removal.")
        return datExpr
    Xcov = pd.concat(X_parts, axis=1)
    # impute simple means for missing covariate values
    Xcov = Xcov.fillna(Xcov.mean())
    keep_signal = md["AD"].astype(float).fillna(md["AD"].mean()).to_frame("AD")
    design = sm.add_constant(pd.concat([keep_signal, Xcov], axis=1).astype(float))

    adj = datExpr.copy()
    cov_cols = list(Xcov.columns)
    for g in datExpr.columns:
        y = datExpr[g].values
        model = sm.OLS(y, design.values).fit()
        beta = pd.Series(model.params, index=design.columns)
        # subtract only the covariate contributions, keep AD + intercept + resid
        adj[g] = y - design[cov_cols].values @ beta[cov_cols].values
    log.info(f"Regressed out covariates {cov_cols} (AD effect preserved).")
    return adj


def drop_invariant_genes(datExpr: pd.DataFrame, cfg: Config, log,
                         sd_floor: float = 1e-8) -> pd.DataFrame:
    """
    Remove genes that are non-finite or have (near-)zero variance.

    WGCNA's goodGenes() does the equivalent. This MUST run after covariate
    adjustment: regressing out sex/region/age can flatten a gene to a constant,
    and a single zero-variance column makes np.corrcoef emit a NaN row/column,
    which then propagates to every connectivity sum and makes the entire
    scale-free fit table NaN (the cause of "Encountered all NA values").
    """
    sd = datExpr.std(axis=0, ddof=1)
    finite = np.isfinite(datExpr.values).all(axis=0)
    keep = (sd.values > sd_floor) & finite
    n_drop = int((~keep).sum())
    if n_drop:
        dropped = list(datExpr.columns[~keep][:10])
        log.warning(
            f"Dropping {n_drop} invariant/non-finite gene(s) after covariate "
            f"adjustment (zero variance breaks the correlation matrix). "
            f"e.g. {dropped}")
    return datExpr.loc[:, keep]


# ==============================================================================
# 3. SOFT-THRESHOLD POWER SELECTION                                      [REV-3]
# ==============================================================================
def adjacency(corr: np.ndarray, power: float, network_type: str) -> np.ndarray:
    if network_type == "signed":
        a = ((1 + corr) / 2.0) ** power
    elif network_type == "signed hybrid":
        a = np.where(corr > 0, corr, 0.0) ** power
    else:  # unsigned
        a = np.abs(corr) ** power
    np.fill_diagonal(a, 0.0)
    return a


def scale_free_fit_index(k: np.ndarray, n_breaks: int = 10):
    """
    Signed scale-free topology fit R^2, mirroring WGCNA::scaleFreeFitIndex.

    Critically, this uses EQUAL-WIDTH bins of connectivity k (R's cut()), NOT
    equal-frequency quantile bins. The log-log regression is log10(p(k)) on
    log10(k); equal-frequency bins force every bin to hold the same number of
    genes, so p(k) is constant, ss_tot == 0, and R^2 is undefined for every
    power. Equal-width bins recover the actual degree distribution, where p(k)
    falls off as k grows (the hallmark of scale-free topology).

    Returns (signed R^2, slope). A good fit has slope < 0, reported as +R^2.
    """
    k = k[np.isfinite(k) & (k >= 0)]
    if len(k) < n_breaks + 1:
        return np.nan, np.nan
    kmin, kmax = float(k.min()), float(k.max())
    if kmax <= kmin:                       # no spread -> undefined
        return np.nan, np.nan
    edges = np.linspace(kmin, kmax, n_breaks + 1)
    mids = 0.5 * (edges[:-1] + edges[1:])
    # right-closed bins, like R's cut(..., right = TRUE)
    binidx = np.clip(np.digitize(k, edges[1:-1], right=True), 0, n_breaks - 1)
    counts = np.bincount(binidx, minlength=n_breaks).astype(float)
    sum_k = np.bincount(binidx, weights=k, minlength=n_breaks)
    # mean k per bin; empty bins fall back to the bin midpoint (WGCNA does this)
    mean_k = np.where(counts > 0, sum_k / np.maximum(counts, 1.0), mids)
    mean_k = np.where(mean_k > 0, mean_k, mids)
    p_k = counts / len(k)
    x = np.log10(mean_k)
    y = np.log10(p_k + 1e-9)               # pseudo-count for empty bins (WGCNA)
    if np.std(x) == 0 or len(x) < 3:
        return np.nan, np.nan
    slope, intercept = np.polyfit(x, y, 1)
    yhat = slope * x + intercept
    ss_res = float(np.sum((y - yhat) ** 2))
    ss_tot = float(np.sum((y - y.mean()) ** 2))
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else np.nan
    return float(-np.sign(slope) * r2), float(slope)  # slope<0 => positive R^2



def pick_soft_threshold(datExpr: pd.DataFrame, cfg: Config, log) -> tuple:
    """
    Mirror WGCNA::pickSoftThreshold. Returns (chosen_power, table DataFrame).
    [REV-3: data-driven beta + diagnostic table/plot, never hard-coded 1]
    """
    corr = np.corrcoef(datExpr.values.T)            # genes x genes
    # Belt-and-suspenders: a residual NaN/inf here (e.g. a constant gene that
    # slipped through) would otherwise poison every connectivity sum and make
    # the whole scale-free table NaN. drop_invariant_genes() should prevent it.
    n_bad = int((~np.isfinite(corr)).sum())
    if n_bad:
        log.warning(f"{n_bad} non-finite entr(ies) in correlation matrix set "
                    f"to 0; check for invariant genes upstream.")
        corr = np.nan_to_num(corr, nan=0.0, posinf=0.0, neginf=0.0)
    np.fill_diagonal(corr, 0.0)
    recs = []
    for p in cfg.powers:
        a = adjacency(corr, p, cfg.network_type)
        k = a.sum(axis=1)
        sft, slope = scale_free_fit_index(k)
        recs.append(dict(power=p, SFT_R2=sft, slope=slope,
                         mean_k=float(k.mean()), median_k=float(np.median(k)),
                         max_k=float(k.max())))
    tab = pd.DataFrame(recs)
    if tab["SFT_R2"].isna().all():
        raise ValueError(
            "Scale-free fit (SFT_R2) is NaN for every candidate power. This "
            "almost always means the gene-gene correlation matrix is "
            "degenerate (constant/duplicated genes or too few samples). "
            "Verify drop_invariant_genes() ran and that datExpr is "
            "samples x genes with adequate variance.")
    eligible = tab[tab["SFT_R2"] >= cfg.sft_r2_cut]
    if getattr(cfg, "manual_power", None):
        chosen = int(cfg.manual_power)
        log.info(f"Using user-specified soft-threshold power beta = {chosen} "
                 f"(--power override; SFT table still written for the record).")
    elif len(eligible):
        chosen = int(eligible["power"].iloc[0])      # lowest power past the cut
    else:
        # R^2 rises monotonically with beta, so idxmax would just return the
        # largest power tested and over-sparsify the network. WGCNA's FAQ
        # instead recommends a sample-size-based default when the R^2 target
        # is never reached. Use that, floored so the network stays connected.
        n_samples = datExpr.shape[0]
        chosen = wgcna_default_power(n_samples, cfg.network_type)
        best_p = int(tab.loc[tab["SFT_R2"].idxmax(), "power"])
        best_r2 = float(tab["SFT_R2"].max())
        log.warning(
            f"No power reached R^2>={cfg.sft_r2_cut} (best R^2={best_r2:.2f} at "
            f"power={best_p}). Falling back to WGCNA sample-size default "
            f"beta={chosen} for n={n_samples} {cfg.network_type} samples. "
            f"Inspect soft_threshold_table.csv; override with --power if needed.")
    log.info(f"Chosen soft-threshold power beta = {chosen} "
             f"(network_type={cfg.network_type})")
    if chosen == 1:
        log.warning("beta==1 selected -- inspect the SFT table; this usually "
                    "indicates a problem and was a key reviewer concern.")
    return chosen, tab, corr


def wgcna_default_power(n_samples: int, network_type: str) -> int:
    """
    WGCNA's recommended soft-threshold power when the scale-free R^2 target is
    not reached, as a function of sample size and network type
    (Langfelder & Horvath WGCNA FAQ). Signed/signed-hybrid networks use roughly
    double the unsigned power.
    """
    signed = network_type in ("signed", "signed hybrid")
    if n_samples < 20:
        return 18 if signed else 9
    if n_samples < 30:
        return 16 if signed else 8
    if n_samples < 40:
        return 14 if signed else 7
    return 12 if signed else 6


# ==============================================================================
# 4. NETWORK CONSTRUCTION (TOM)                                          [REV-3]
# ==============================================================================
def topological_overlap(a: np.ndarray) -> np.ndarray:
    """Unsigned TOM (works on non-negative signed adjacency too)."""
    L = a @ a                                   # shared-neighbour connectivity
    k = a.sum(axis=1)
    k_min = np.minimum.outer(k, k)
    denom = k_min + 1 - a
    tom = (L + a) / denom
    np.fill_diagonal(tom, 1.0)
    tom = np.clip(tom, 0, 1)
    return tom


# ==============================================================================
# 5. MODULE DETECTION                                                    [REV-4,8]
# ==============================================================================
def detect_modules(dissTOM: np.ndarray, genes, cfg: Config, log) -> pd.Series:
    from dynamicTreeCut import cutreeHybrid
    Z = linkage(squareform(dissTOM, checks=False), method="average")
    # NOTE: the dynamicTreeCut PyPI port has a defect in its
    # pamRespectsDendro=False branch (references an undefined name). We therefore
    # use pamRespectsDendro=True (the WGCNA-default behaviour, and bug-free),
    # and fall back to pamStage=False if any PAM-stage error is raised.
    try:
        cut = cutreeHybrid(Z, distM=dissTOM, deepSplit=cfg.deep_split,
                           minClusterSize=cfg.min_module_size,
                           pamRespectsDendro=True, verbose=0)
    except Exception as e:
        log.warning(f"PAM stage failed ({e}); retrying with pamStage=False.")
        cut = cutreeHybrid(Z, distM=dissTOM, deepSplit=cfg.deep_split,
                           minClusterSize=cfg.min_module_size,
                           pamStage=False, verbose=0)
    labels = pd.Series(cut["labels"], index=genes, name="module")
    log.info(f"Dynamic tree cut -> {labels.nunique()} raw modules "
             f"(incl. label 0 = unassigned/grey).")
    return labels, Z


def module_eigengenes(datExpr: pd.DataFrame, labels: pd.Series) -> pd.DataFrame:
    """First PC per module, sign-aligned to mean expression."""
    MEs = {}
    for m in sorted(labels.unique()):
        if m == 0:
            continue
        genes = labels.index[labels == m]
        X = datExpr[genes].values
        X = (X - X.mean(0)) / (X.std(0) + 1e-9)
        u, s, vt = np.linalg.svd(X, full_matrices=False)
        pc1 = u[:, 0] * s[0]
        # sign alignment
        if np.corrcoef(pc1, X.mean(1))[0, 1] < 0:
            pc1 = -pc1
        MEs[f"ME{m}"] = pc1
    return pd.DataFrame(MEs, index=datExpr.index)


def merge_close_modules(datExpr, labels, cfg, log):
    """Merge modules whose eigengenes correlate > 1 - merge_cut_height. [REV-8]"""
    MEs = module_eigengenes(datExpr, labels)
    if MEs.shape[1] <= 1:
        return labels, MEs
    cor = np.corrcoef(MEs.values.T)
    diss = 1 - cor
    Z = linkage(squareform(np.clip(diss, 0, 2), checks=False), method="average")
    grp = fcluster(Z, t=cfg.merge_cut_height, criterion="distance")
    me_names = list(MEs.columns)
    old2new = {}
    for me_name, g in zip(me_names, grp):
        old = int(me_name[2:])
        old2new[old] = g
    new_labels = labels.copy()
    mask = new_labels != 0
    new_labels[mask] = new_labels[mask].map(old2new)
    log.info(f"Module merge (cutHeight={cfg.merge_cut_height}): "
             f"{labels[labels!=0].nunique()} -> {new_labels[new_labels!=0].nunique()} modules.")
    MEs = module_eigengenes(datExpr, new_labels)
    return new_labels, MEs


# WGCNA standardColors() order; integer label 0 is the unassigned ("grey")
# module. These are real R colour names so the R companion's preservation
# plot (bg = module) renders, and modulePreservation correctly excludes grey.
WGCNA_COLORS = [
    "turquoise", "blue", "brown", "yellow", "green", "red", "black", "pink",
    "magenta", "purple", "greenyellow", "tan", "salmon", "cyan", "midnightblue",
    "lightcyan", "grey60", "lightgreen", "lightyellow", "royalblue", "darkred",
    "darkgreen", "darkturquoise", "darkgrey", "orange", "darkorange", "white",
    "skyblue", "saddlebrown", "steelblue", "paleturquoise", "violet",
    "darkolivegreen", "darkmagenta",
]


def label_to_color(m) -> str:
    """Map an integer module label to a WGCNA colour name (0 -> grey)."""
    m = int(m)
    if m == 0:
        return "grey"
    idx = m - 1
    return WGCNA_COLORS[idx] if 0 <= idx < len(WGCNA_COLORS) else f"module{m}"


def module_size_table(labels: pd.Series, n_genes: int, log) -> pd.DataFrame:
    """[REV-4] sizes MUST sum to n_genes; enforced by assertion."""
    sizes = labels.value_counts().sort_index()
    tab = sizes.rename("n_genes").reset_index()
    tab.columns = ["module_label", "n_genes"]
    tab["color"] = tab["module_label"].apply(label_to_color)
    tab["module"] = tab["module_label"].apply(
        lambda m: "grey(unassigned)" if m == 0 else f"M{m}")
    tab = tab[["module", "color", "n_genes"]]
    total = int(sizes.sum())
    assert total == n_genes, (
        f"[REV-4] Module sizes sum to {total} but {n_genes} genes were analysed. "
        "This is exactly the inconsistency reviewers flagged.")
    log.info("Module sizes (sum == n_genes, verified):\n" + tab.to_string(index=False))
    return tab


# ==============================================================================
# 6. MODULE-TRAIT RELATIONSHIPS                                          [REV-8,9]
# ==============================================================================
def correlate_pvalue(x, y):
    x = np.asarray(x, float); y = np.asarray(y, float)
    ok = ~(np.isnan(x) | np.isnan(y))
    x, y = x[ok], y[ok]
    n = len(x)
    if n < 4 or x.std() == 0 or y.std() == 0:
        return np.nan, np.nan
    r = np.corrcoef(x, y)[0, 1]
    tval = r * np.sqrt((n - 2) / max(1e-12, 1 - r ** 2))
    p = 2 * t_dist.sf(abs(tval), df=n - 2)
    return float(r), float(p)


def module_trait(MEs: pd.DataFrame, meta: pd.DataFrame, cfg: Config, log):
    """
    Correlate every module eigengene with binary AD status AND continuous
    pathology traits (braak) plus covariates for transparency. Report exact
    BH-adjusted p-values. [REV-8 reconcile biology, REV-9 exact padj & traits]
    """
    traits = {}
    md = meta.loc[MEs.index]
    traits["AD_status"] = md["AD"].astype(float)
    for t in ("braak", "age", "sex"):
        if t in md.columns and md[t].notna().sum() > 4:
            traits[t] = md[t].astype(float)
    rows = []
    for me in MEs.columns:
        for tname, tvals in traits.items():
            r, p = correlate_pvalue(MEs[me].values, tvals.values)
            rows.append(dict(module=me, trait=tname, r=r, p=p))
    res = pd.DataFrame(rows)
    res["p_adj_BH"] = np.nan
    ok = res["p"].notna()
    res.loc[ok, "p_adj_BH"] = multipletests(res.loc[ok, "p"], method="fdr_bh")[1]
    sig = res[(res["trait"] == "AD_status")
              & (res["r"].abs() >= cfg.mt_abs_r_cut)
              & (res["p_adj_BH"] < cfg.mt_padj_cut)].copy()
    log.info(f"Modules significantly associated with AD status "
             f"(|r|>={cfg.mt_abs_r_cut}, padj<{cfg.mt_padj_cut}): "
             f"{sig['module'].tolist()}")
    return res, sig


# ==============================================================================
# 7. GENE SIGNIFICANCE, MODULE MEMBERSHIP, HUB GENES                     [REV-8]
# ==============================================================================
def gs_mm_hub(datExpr, labels, MEs, meta, cfg, log):
    ad = meta.loc[datExpr.index, "AD"].astype(float).values
    GS = {}
    for g in datExpr.columns:
        r, _ = correlate_pvalue(datExpr[g].values, ad)
        GS[g] = abs(r) if r == r else np.nan
    GS = pd.Series(GS, name="GS")

    MM = pd.Series(index=datExpr.columns, dtype=float, name="MM")
    for g in datExpr.columns:
        m = labels[g]
        if m == 0 or f"ME{m}" not in MEs.columns:
            continue
        r, _ = correlate_pvalue(datExpr[g].values, MEs[f"ME{m}"].values)
        MM[g] = r
    df = pd.concat([labels.rename("module"), GS, MM], axis=1)
    df["is_hub"] = (df["MM"].abs() >= cfg.hub_mm_cut) & (df["GS"] >= cfg.hub_gs_cut)
    df["is_AD_risk_gene"] = df.index.isin(AD_RISK_GENES)
    log.info(f"Hub genes (MM>={cfg.hub_mm_cut} & GS>={cfg.hub_gs_cut}): "
             f"{int(df['is_hub'].sum())}")
    return df


# ==============================================================================
# 8. AD RISK-GENE ENRICHMENT (Fisher exact, explicit background)         [REV-9]
# ==============================================================================
def risk_gene_enrichment(labels: pd.Series, log) -> pd.DataFrame:
    """
    Background = all genes that entered the network (NOT the whole genome).
    [REV-9: background explicitly the analysis universe]
    """
    universe = set(labels.index)
    risk_in_universe = universe & set(AD_RISK_GENES)
    log.info(f"AD risk genes present in analysis universe: "
             f"{len(risk_in_universe)}/{len(AD_RISK_GENES)}")
    rows = []
    for m in sorted(labels.unique()):
        if m == 0:
            continue
        mod_genes = set(labels.index[labels == m])
        a = len(mod_genes & risk_in_universe)          # risk & in module
        b = len(mod_genes) - a                          # non-risk & in module
        c = len(risk_in_universe) - a                   # risk & not in module
        d = len(universe) - a - b - c
        OR, p = fisher_exact([[a, b], [c, d]], alternative="greater")
        rows.append(dict(module=f"ME{m}", n_module=len(mod_genes),
                         n_risk_in_module=a, odds_ratio=OR, p=p,
                         risk_genes=";".join(sorted(mod_genes & risk_in_universe))))
    res = pd.DataFrame(rows)
    if len(res):
        res["p_adj_BH"] = multipletests(res["p"], method="fdr_bh")[1]
        res = res.sort_values("p")
    log.info("AD risk-gene enrichment per module:\n" +
             res[["module", "n_module", "n_risk_in_module",
                  "odds_ratio", "p", "p_adj_BH"]].to_string(index=False))
    return res


# ==============================================================================
# 9. FUNCTIONAL ENRICHMENT (GO / KEGG)                                   [REV-8,9]
# ==============================================================================
def functional_enrichment(labels, sig_modules, cfg, out_dir, log):
    """
    Run Enrichr for EVERY non-grey module with an explicit background, writing
    enrichment_ME*.csv per module. Module biology is read FROM this output, not
    asserted [REV-8]. We enrich all modules (not only trait-significant ones)
    because the most interpretable module biologically may be a risk-gene or
    preservation hit rather than a case/control hit (e.g. a microglial module
    that is strongly GWAS-enriched but only weakly trait-correlated).
    """
    if not cfg.run_enrichr:
        log.info("run_enrichr=False -> skipping GO/KEGG (offline mode).")
        return {}
    import gseapy as gp
    background = list(labels.index)
    sig_set = set(sig_modules)
    all_modules = [f"ME{m}" for m in sorted(labels.unique()) if m != 0]
    summaries = {}
    for me in all_modules:
        m = int(me[2:])
        genes = list(labels.index[labels == m])
        if len(genes) < 5:
            continue
        try:
            enr = gp.enrichr(gene_list=genes, gene_sets=list(cfg.enrichr_gene_sets),
                             background=background, outdir=None)
            res = enr.results
            res = res[res["Adjusted P-value"] < cfg.enrichment_fdr_cut]
            res = res.sort_values("Adjusted P-value")
            res.to_csv(os.path.join(out_dir, f"enrichment_{me}.csv"), index=False)
            top_terms = res["Term"].head(5).tolist()
            summaries[me] = top_terms
            tag = " [trait-significant]" if me in sig_set else ""
            log.info(f"{me}{tag}: {len(res)} terms at FDR<{cfg.enrichment_fdr_cut}; "
                     f"top: {top_terms}")
        except Exception as e:                          # network / API issues
            log.warning(f"Enrichr failed for {me}: {e}. "
                        "Re-run with internet access or use a local GMT.")
    return summaries


# ==============================================================================
# 10. MODULE PRESERVATION (independent dataset)                          [REV-7]
# ==============================================================================
def module_preservation(disc_expr, disc_labels, val_expr, cfg, log):
    """
    Permutation-based approximation of WGCNA::modulePreservation Z-summary.
    For each discovery module we test, in the VALIDATION cohort, two stable
    statistics (Langfelder et al. 2011, simplified):
      density      : meanCor  = mean pairwise |correlation| among the module's
                     genes in the validation data (high if the module stays
                     densely co-expressed).
      connectivity : cor.kME  = correlation between each gene's connectivity to
                     the module eigengene in DISCOVERY vs VALIDATION (high if the
                     internal connectivity ranking is reproduced).
    Z = (observed - mean_permuted) / sd_permuted, with random equal-sized gene
    sets as the null; Z is clipped to +/-50 for numerical stability.
    Zsummary = mean(Zdensity, Zconnectivity).
    Thresholds: Zsummary > 10 strong, 2-10 moderate, < 2 not preserved.
    NOTE: for a publication-grade statistic, ALSO run WGCNA::modulePreservation
    in R (see the ad_wgcna_validation.R companion). [REV-7]
    """
    rng = np.random.default_rng(cfg.seed)
    common = sorted(set(disc_expr.columns) & set(val_expr.columns))
    log.info(f"Preservation: {len(common)} genes common to discovery & validation.")
    if len(common) > cfg.preservation_max_genes:
        v = val_expr[common].var().sort_values(ascending=False)
        common = list(v.index[:cfg.preservation_max_genes])
    disc_e = disc_expr[common]; val_e = val_expr[common]
    lab = disc_labels.loc[common]

    val_corr = np.corrcoef(val_e.values.T); np.fill_diagonal(val_corr, 0)
    disc_corr = np.corrcoef(disc_e.values.T); np.fill_diagonal(disc_corr, 0)
    gene_idx = {g: i for i, g in enumerate(common)}

    def density_stat(idx):
        sub = np.abs(val_corr[np.ix_(idx, idx)])
        return sub[np.triu_indices(len(idx), 1)].mean()

    def conn_stat(idx):
        # cor.cor: agreement between the pairwise-correlation PATTERNS of the
        # module in discovery vs validation (robust; no kME-variance dependence).
        iu = np.triu_indices(len(idx), 1)
        cd = disc_corr[np.ix_(idx, idx)][iu]
        cv = val_corr[np.ix_(idx, idx)][iu]
        if cd.std() < 1e-6 or cv.std() < 1e-6:
            return 0.0
        return abs(np.corrcoef(cd, cv)[0, 1])

    def _z(obs, perm):
        perm = np.asarray(perm)
        sd = perm.std()
        if sd < 1e-6:
            return 0.0
        return float(np.clip((obs - perm.mean()) / sd, -50, 50))

    results = []
    for m in sorted(lab.unique()):
        if m == 0:
            continue
        mgenes = [g for g in common if lab[g] == m]
        if len(mgenes) < cfg.min_module_size:
            continue
        ii = np.array([gene_idx[g] for g in mgenes])
        obs_d = density_stat(ii); obs_c = conn_stat(ii)
        perm_d, perm_c = [], []
        for _ in range(cfg.preservation_perms):
            ridx = rng.choice(len(common), size=len(ii), replace=False)
            perm_d.append(density_stat(ridx)); perm_c.append(conn_stat(ridx))
        Zd = _z(obs_d, perm_d); Zc = _z(obs_c, perm_c)
        Zsum = np.mean([Zd, Zc])
        verdict = ("strong" if Zsum > 10 else
                   "moderate" if Zsum > 2 else "not preserved")
        results.append(dict(module=f"ME{m}", n_genes=len(mgenes),
                            meanCor=round(obs_d, 3), corCor=round(obs_c, 3),
                            Zdensity=round(Zd, 2), Zconnectivity=round(Zc, 2),
                            Zsummary=round(Zsum, 2), preservation=verdict))
    res = pd.DataFrame(results).sort_values("Zsummary", ascending=False)
    res["medianRank"] = res["Zsummary"].rank(ascending=False).astype(int)
    log.info("Module preservation (Zsummary):\n" + res.to_string(index=False))
    return res


# ==============================================================================
# 11. FIGURES (analysis-derived only)                                    [REV-6]
# ==============================================================================
def make_figures(sft_tab, mt_res, MEs, meta, labels, gsmm, out_dir, log):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import seaborn as sns

    # Fig A: scale-free topology + mean connectivity [REV-3]
    fig, ax = plt.subplots(1, 2, figsize=(11, 4.2))
    ax[0].plot(sft_tab["power"], sft_tab["SFT_R2"], "o-")
    ax[0].axhline(CFG.sft_r2_cut, ls="--", c="r")
    ax[0].set(xlabel="Soft-threshold power (beta)",
              ylabel="Scale-free topology fit R^2",
              title="Scale-free topology criterion")
    ax[1].plot(sft_tab["power"], sft_tab["mean_k"], "o-")
    ax[1].set(xlabel="Soft-threshold power (beta)", ylabel="Mean connectivity",
              title="Mean connectivity")
    fig.tight_layout(); fig.savefig(os.path.join(out_dir, "fig_soft_threshold.png"),
                                    dpi=150); plt.close(fig)

    # Fig B: module-trait heatmap [REV-8]
    piv = mt_res.pivot(index="module", columns="trait", values="r")
    pp = mt_res.pivot(index="module", columns="trait", values="p_adj_BH")
    annot = piv.round(2).astype(str) + "\n(" + pp.map(
        lambda x: f"{x:.1e}" if x == x else "na") + ")"
    fig, ax = plt.subplots(figsize=(1.6 + 1.2 * piv.shape[1], 0.5 * piv.shape[0] + 2))
    sns.heatmap(piv, annot=annot, fmt="", cmap="RdBu_r", center=0,
                vmin=-1, vmax=1, ax=ax, cbar_kws={"label": "Pearson r"})
    ax.set_title("Module-trait relationships (r and BH-adjusted p)")
    fig.tight_layout(); fig.savefig(os.path.join(out_dir, "fig_module_trait.png"),
                                    dpi=150); plt.close(fig)

    log.info("Saved analysis figures: fig_soft_threshold.png, fig_module_trait.png")


# ==============================================================================
# MAIN
# ==============================================================================
def run(cfg: Config, skip_download: bool):
    np.random.seed(cfg.seed)
    out_dir = cfg.out_dir
    log = setup_logging(out_dir)
    log.info("=" * 70)
    log.info("AD WGCNA reproducible pipeline")
    log.info(f"Primary dataset (REV-1): {cfg.primary_gse} | "
             f"network_type={cfg.network_type} | seed={cfg.seed}")
    log.info("=" * 70)

    # --- 1. Discovery data --------------------------------------------------
    gse = download_geo(cfg.primary_gse, cfg, log)
    expr = build_expression_matrix(gse, log)
    expr = map_probes_to_genes(gse, expr, log)
    meta = parse_metadata(gse, log)

    # keep only samples with known diagnosis
    meta = meta[meta["AD"].notna()]
    expr = expr[meta.index]
    expr = maybe_log2(expr, log)
    expr = filter_genes(expr, cfg, log)

    datExpr = expr.T                                # samples x genes
    datExpr = detect_sample_outliers(datExpr, cfg, log)
    meta = meta.loc[datExpr.index]
    datExpr = adjust_covariates(datExpr, meta, cfg, log)
    datExpr = drop_invariant_genes(datExpr, cfg, log)
    n_genes = datExpr.shape[1]
    log.info(f"FINAL discovery matrix: {datExpr.shape[0]} samples x {n_genes} genes")

    # --- 3. Soft threshold --------------------------------------------------
    beta, sft_tab, corr = pick_soft_threshold(datExpr, cfg, log)
    sft_tab.to_csv(os.path.join(out_dir, "soft_threshold_table.csv"), index=False)

    # --- 4. Network ---------------------------------------------------------
    adj = adjacency(corr, beta, cfg.network_type)
    TOM = topological_overlap(adj)
    dissTOM = 1 - TOM

    # --- 5. Modules ---------------------------------------------------------
    raw_labels, _ = detect_modules(dissTOM, datExpr.columns, cfg, log)
    labels, MEs = merge_close_modules(datExpr, raw_labels, cfg, log)
    size_tab = module_size_table(labels, n_genes, log)        # asserts sum==n_genes
    size_tab.to_csv(os.path.join(out_dir, "module_sizes.csv"), index=False)

    # --- inputs for the R preservation companion (ad_wgcna_validation.R) -----
    # discovery_expr.csv : genes (rows) x samples (cols)
    datExpr.T.to_csv(os.path.join(out_dir, "discovery_expr.csv"))
    # module_colors.csv : gene,module  (module = WGCNA colour; grey = unassigned)
    mc = labels.map(label_to_color).reset_index()
    mc.columns = ["gene", "module"]
    mc.to_csv(os.path.join(out_dir, "module_colors.csv"), index=False)
    log.info("Wrote R-companion inputs: discovery_expr.csv, module_colors.csv "
             "(validation_expr.csv is written during the preservation step).")

    # --- 6. Module-trait ----------------------------------------------------
    mt_res, sig = module_trait(MEs, meta, cfg, log)
    mt_res.to_csv(os.path.join(out_dir, "module_trait.csv"), index=False)
    sig_modules = sig["module"].tolist()

    # --- 7. GS / MM / hubs --------------------------------------------------
    gsmm = gs_mm_hub(datExpr, labels, MEs, meta, cfg, log)
    gsmm.to_csv(os.path.join(out_dir, "gene_significance_module_membership.csv"))

    # --- 8. Risk-gene enrichment -------------------------------------------
    risk = risk_gene_enrichment(labels, log)
    risk.to_csv(os.path.join(out_dir, "risk_gene_enrichment.csv"), index=False)

    # --- 9. Functional enrichment ------------------------------------------
    enr_summary = functional_enrichment(labels, sig_modules, cfg, out_dir, log)

    # --- 10. Preservation ---------------------------------------------------
    preservation = None
    try:
        gse_val = download_geo(cfg.validation_gse, cfg, log)
        val_expr = build_expression_matrix(gse_val, log)
        val_expr = map_probes_to_genes(gse_val, val_expr, log)
        val_expr = maybe_log2(val_expr, log).T          # samples x genes
        # validation_expr.csv for the R companion: genes (rows) x samples (cols),
        # restricted to the discovery gene set the modules are defined on.
        common_val = [g for g in datExpr.columns if g in val_expr.columns]
        val_expr[common_val].T.to_csv(
            os.path.join(out_dir, "validation_expr.csv"))
        log.info(f"Wrote validation_expr.csv ({len(common_val)} genes shared "
                 f"with discovery) for the R companion.")
        preservation = module_preservation(datExpr, labels, val_expr, cfg, log)
        preservation.to_csv(os.path.join(out_dir, "module_preservation.csv"), index=False)
    except Exception as e:
        log.warning(f"Preservation step skipped ({e}). "
                    "Run with internet access to GEO, or use the R companion.")

    # --- 11. Figures --------------------------------------------------------
    make_figures(sft_tab, mt_res, MEs, meta, labels, gsmm, out_dir, log)

    # --- run manifest (reproducibility) ------------------------------------
    manifest = dict(
        timestamp=datetime.now().isoformat(timespec="seconds"),
        primary_dataset=cfg.primary_gse, validation_dataset=cfg.validation_gse,
        n_samples=int(datExpr.shape[0]), n_genes=int(n_genes),
        network_type=cfg.network_type, beta=beta,
        n_modules=int(labels[labels != 0].nunique()),
        ad_associated_modules=sig_modules,
        enrichment_summary=enr_summary,
        config={k: (list(v) if isinstance(v, tuple) else v)
                for k, v in cfg.__dict__.items()},
        package_versions={p: __import__(p).__version__ for p in
                          ["numpy", "pandas", "scipy", "sklearn",
                           "statsmodels", "gseapy"]},
    )
    with open(os.path.join(out_dir, "run_manifest.json"), "w") as fh:
        json.dump(manifest, fh, indent=2, default=str)
    log.info(f"Done. All outputs in ./{out_dir}/")
    log.info("Use module_sizes.csv, module_trait.csv, risk_gene_enrichment.csv, "
             "enrichment_*.csv and module_preservation.csv as the manuscript's "
             "quantitative tables (replace the descriptive bullet lists).")


def main():
    ap = argparse.ArgumentParser(description="Reproducible AD WGCNA pipeline")
    ap.add_argument("--skip-download", action="store_true",
                    help="reuse cached GEO files in geo_cache/")
    ap.add_argument("--network-type", default=CFG.network_type,
                    choices=["signed", "unsigned", "signed hybrid"])
    ap.add_argument("--no-enrichr", action="store_true",
                    help="skip GO/KEGG (offline mode)")
    ap.add_argument("--primary", default=CFG.primary_gse)
    ap.add_argument("--validation", default=CFG.validation_gse)
    ap.add_argument("--power", type=int, default=0,
                    help="Override soft-threshold beta (0 = data-driven). Use "
                         "after inspecting results/soft_threshold_table.csv.")
    args = ap.parse_args()
    CFG.network_type = args.network_type
    CFG.run_enrichr = not args.no_enrichr
    CFG.primary_gse = args.primary
    CFG.validation_gse = args.validation
    CFG.manual_power = args.power
    run(CFG, args.skip_download)


if __name__ == "__main__":
    main()

